apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eks-app-deployment
  namespace: my-eks-app
  labels:
    app: my-eks-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-eks-app-test1
  template:
    metadata:
      name: mypod
      labels:
        app: my-eks-app-test1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: testapp-1-eks
        image: elexad/simple-web-ec2:1.5
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
