apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: myapp
    type: full-stack
spec:
  #Pod definition see replicaset-definition.yaml
  template:
    metadata: 
      name: mypod
      labels:
        app: my-test-app
        tier: fullstack
    spec:
      containers:
      - name: testapp1
        image: elexad/webapp-test:1.0
  replicas: 3
  selector:
    matchLabels: #label of the pod must match
      tier: fullstack
