apiVersion: v1
kind: Service #for external communication in private subnet
metadata:
  name: my-test-servicw-np
  namespace: my-eks-app
  labels:
    app: my-eks-app-nodeport
spec:
  type: NodePort
  ports: 
   - targetPort: 80
     port: 80
     nodePort: 30008
  selector: 
    app: my-eks-app-test1 #for my-eks-app-test1, this comes from pod