apiVersion: v1
kind: Service #for internal communication in private subnet
metadata:
  name: my-test-service
  namespace: my-eks-app
  labels:
    app: my-eks-app-cluster-ip
spec:
  type: ClusterIP
  ports: 
   - targetPort: 6379 # backend port
     port: 6379 # service port
  selector: 
    app: my-eks-app-test1 #for my-eks-app-test1, this comes from pod